VAR1 =cint(inputbox(" Enter The no 1"))
VAR2=cint(INPUTBOX("Enter The no 2"))

opration=inputbox("+  -  *  /")

IF opration = "+" then
msgbox(" Sum = "&(VAR1+VAR2))
ELSEIF opration = "-" then
msgbox(" Sub = "&(VAR1-VAR2))
ELSEIF opration = "*" then
msgbox(" Multi = "&(VAR1*VAR2))
ELSEIF opration = "/" then
msgbox(" Div= "&(VAR1/VAR2))
else
msgbox("Not Valid Opration Is Selected")
end if











